# Στάδιο 1: Χτίσιμο (Build)
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app

# Αντιγράφουμε τα αρχεία χρησιμοποιώντας τη διαδρομή του φακέλου backend
COPY backend/pom.xml .
COPY backend/src ./src

RUN mvn clean package -DskipTests

# Στάδιο 2: Εκτέλεση (Run)
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]